services:
  mysql:
    container_name: music_mysql
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - "./docker_data/mysql:/var/lib/mysql"
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Root.123456
      - MYSQL_DATABASE=pkmer_music