package io.gitee.pkmer.core.infrastructure.persistence.banner.mybatis;


import lombok.Data;

/**
 * generated by MyBatis Generator.
 * banner() 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2025/01/05
 */
@Data
public class Banner {
    private Long id;

    private String pic;

}