package io.gitee.pkmer.core.infrastructure.persistence.singer.mybatis;

import io.gitee.pkmer.mybatis.annotations.SnowflakeId;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * generated by MyBatis Generator.
 * singer(歌手) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2025/01/10
 */
@Data
public class Singer {

    @SnowflakeId
    private Long id;


    private String name;


    private Byte sex;


    private String pic;


    private LocalDateTime birth;


    private String location;


    private String introduction;


}