packages:
  - "apps/*"
  - "packages/*"
catalogs:
  # Can be referenced through "catalog:react17"
  react19:
    next: 15.1.2
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19
    "@types/react-dom": ^19


  vue3:
    pinia: ^2.2.6
    vue: ^3.5.13
    vue-router: ^4.4.5

  node:
    "@types/node": ^20

