package io.gitee.pkmer.minio.repository.mybatis;

import jakarta.annotation.Generated;
import java.time.LocalDateTime;

/**
 * generated by MyBatis Generator.
 * file_metadata_info(文件元数据信息表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2025/01/18
 */
public class FileMetadataInfo {
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long id;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String fileKey;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String fileMd5;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String fileName;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String fileMimeType;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String fileSuffix;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long fileSize;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Boolean isPreview;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Boolean isPrivate;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String bucket;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String bucketPath;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String uploadId;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String etag;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Boolean isFinished;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Boolean isPart;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Integer partNumber;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private LocalDateTime createTime;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String createUser;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private LocalDateTime updateTime;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String updateUser;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getId() {
        return id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getFileKey() {
        return fileKey;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setFileKey(String fileKey) {
        this.fileKey = fileKey;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getFileMd5() {
        return fileMd5;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getFileName() {
        return fileName;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getFileMimeType() {
        return fileMimeType;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setFileMimeType(String fileMimeType) {
        this.fileMimeType = fileMimeType;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getFileSuffix() {
        return fileSuffix;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setFileSuffix(String fileSuffix) {
        this.fileSuffix = fileSuffix;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getFileSize() {
        return fileSize;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Boolean getIsPreview() {
        return isPreview;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setIsPreview(Boolean isPreview) {
        this.isPreview = isPreview;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Boolean getIsPrivate() {
        return isPrivate;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setIsPrivate(Boolean isPrivate) {
        this.isPrivate = isPrivate;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getBucket() {
        return bucket;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setBucket(String bucket) {
        this.bucket = bucket;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getBucketPath() {
        return bucketPath;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setBucketPath(String bucketPath) {
        this.bucketPath = bucketPath;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getUploadId() {
        return uploadId;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setUploadId(String uploadId) {
        this.uploadId = uploadId;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getEtag() {
        return etag;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setEtag(String etag) {
        this.etag = etag;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Boolean getIsFinished() {
        return isFinished;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setIsFinished(Boolean isFinished) {
        this.isFinished = isFinished;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Boolean getIsPart() {
        return isPart;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setIsPart(Boolean isPart) {
        this.isPart = isPart;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Integer getPartNumber() {
        return partNumber;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setPartNumber(Integer partNumber) {
        this.partNumber = partNumber;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getCreateUser() {
        return createUser;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getUpdateUser() {
        return updateUser;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
}