package io.gitee.pkmer.core.dao.model.banner;

import io.gitee.pkmer.mybatis.annotations.SnowflakeId;
import jakarta.annotation.Generated;
import lombok.Data;

/**
 * generated by MyBatis Generator.
 * banner() 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2025/01/02
 */
@Data
public class Banner {
    @SnowflakeId
    private Long id;
    private String pic;
}