[versions]
org-springframework-boot="3.4.1"
jjwt="0.12.6"
lombok="1.18.36"
flywaydb="11.1.0"
minio="8.5.11"
mybatis-plus="3.5.9"
mybatis-plus-generator="3.5.9"
p6spy="1.10.0"
[libraries]
jjwt = {module = "io.jsonwebtoken:jjwt",version.ref="jjwt"}
lombok = {module = "org.projectlombok:lombok",version.ref="lombok"}
minio={module="io.minio:minio",version.ref="minio"}
mybatis-plus={module="com.baomidou:mybatis-plus-spring-boot3-starter",version.ref="mybatis-plus"}
mybatis-plus-generator={module="com.baomidou:mybatis-plus-generator",version.ref="mybatis-plus-generator"}
p6spy={module="com.github.gavlyukovskiy:p6spy-spring-boot-starter",version.ref="p6spy"}
[plugins]
org-springframework-boot={id = "org.springframework.boot",version.ref = "org-springframework-boot"}
flywaydb={id = "org.flywaydb.flyway",version.ref="flywaydb"}
