[versions]
org-springframework-boot="3.4.1"
jjwt="0.12.6"
lombok="1.18.36"
flywaydb="11.1.0"
[libraries]
jjwt = {module = "io.jsonwebtoken:jjwt",version.ref="jjwt"}
lombok = {module = "org.projectlombok:lombok",version.ref="lombok"}
[plugins]
org-springframework-boot={id = "org.springframework.boot",version.ref = "org-springframework-boot"}
flywaydb={id = "org.flywaydb.flyway",version.ref="flywaydb"}