package io.gitee.pkmer.core.infrastructure.persistence.collect.mybatis;

import io.gitee.pkmer.mybatis.annotations.SnowflakeId;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * generated by MyBatis Generator.
 * collect(收藏表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2025/01/10
 */
@Data
public class Collect {

    @SnowflakeId
    private Long id;


    private Long userId;


    private Byte type;


    private Long songId;


    private Long songListId;


    private LocalDateTime createTime;
}