package io.gitee.pkmer.core.infrastructure.persistence.song.mybatis;

import io.gitee.pkmer.mybatis.annotations.SnowflakeId;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * generated by MyBatis Generator.
 * song(歌曲) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2025/01/09
 */
@Data
public class Song {
    @SnowflakeId
    private Long id;

    private Integer singerId;

    private String name;

    private String introduction;

    private LocalDateTime createTime;

    private LocalDateTime updateTime;

    private String pic;

    private String url;

    private String lyric;
}