package io.gitee.pkmer.core.infrastructure.persistence.songlist.mybatis;

import io.gitee.pkmer.mybatis.annotations.SnowflakeId;
import lombok.Data;

/**
 * generated by MyBatis Generator.
 * song_list(歌单表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2025/01/05
 */
@Data
public class SongList {
    @SnowflakeId
    private Long id;

    private String title;

    private String pic;

    private String style;

    private String introduction;

}