package io.gitee.pkmer.core.infrastructure.persistence.songlist.mybatis;

import jakarta.annotation.Generated;

/**
 * generated by MyBatis Generator.
 * list_song(歌单歌曲关联表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2025/01/10
 */
public class ListSong {
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long id;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long songId;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long songListId;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getId() {
        return id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getSongId() {
        return songId;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setSongId(Long songId) {
        this.songId = songId;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getSongListId() {
        return songListId;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setSongListId(Long songListId) {
        this.songListId = songListId;
    }
}