package io.gitee.pkmer.core.infrastructure.persistence.comment.mybatis;

import jakarta.annotation.Generated;
import java.time.LocalDateTime;

/**
 * generated by MyBatis Generator.
 * comment(评论表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2025/01/10
 */
public class Comment {
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long id;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long userId;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long songId;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Long songListId;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private String content;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private LocalDateTime createTime;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Byte type;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    private Integer up;

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getId() {
        return id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getUserId() {
        return userId;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getSongId() {
        return songId;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setSongId(Long songId) {
        this.songId = songId;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Long getSongListId() {
        return songListId;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setSongListId(Long songListId) {
        this.songListId = songListId;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public String getContent() {
        return content;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setContent(String content) {
        this.content = content;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Byte getType() {
        return type;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setType(Byte type) {
        this.type = type;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public Integer getUp() {
        return up;
    }

    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    public void setUp(Integer up) {
        this.up = up;
    }
}