package io.gitee.pkmer.core.infrastructure.persistence.consumer.mybatis;

import io.gitee.pkmer.mybatis.annotations.SnowflakeId;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * generated by MyBatis Generator.
 * consumer(用户表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2025/01/10
 */
@Data
public class Consumer {

    @SnowflakeId
    private Long id;


    private String username;


    private String password;


    private Byte sex;


    private String phoneNum;


    private String email;


    private LocalDateTime birth;


    private String introduction;


    private String location;


    private String avator;


    private LocalDateTime createTime;


    private LocalDateTime updateTime;
}