package io.gitee.pkmer.core.infrastructure.persistence.admin.mybatis;

import io.gitee.pkmer.mybatis.annotations.SnowflakeId;
import lombok.Data;

/**
 * generated by MyBatis Generator.
 * management_admin(管理员信息表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2025/02/17
 */
@Data
public class ManagementAdmin {
    @SnowflakeId
    private Long id;

    private String name;

    private String password;
}