spring:
  datasource:
      url: jdbc:mysql://localhost:3309/pkmer_music?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Root.123456
      driver-class-name: com.mysql.cj.jdbc.Driver
pkmer:
  minio:
    access-key: root
    secret-key: Root.123456
    url: http:localhost:9000