spring:
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB
  datasource:
      url: jdbc:mysql://localhost:3309/pkmer_music?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Root.123456
      driver-class-name: com.mysql.cj.jdbc.Driver
decorator:
  datasource:
    p6spy:
      # 日志格式
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
      # 自定义日志类
      logging: custom
      custom-appender-class: io.gitee.pkmer.logger.StdoutLogger

pkmer:
  minio:
    access-key: root
    secret-key: Root.123456
    url: http://localhost:9000
    default-chunk-size: 10MB # MinIO的分片上传最小值是5MB，任何小于这个大小的分片都会导致错误。
    expires: 12h



mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    mybatis: DEBUG
    org.mybatis: DEBUG
app:
  jwt:
    secret-key: 9cZjXN9uHH0erCgOAdZCsXIAJbeh7Q43eLa/c1a69rU=
    expiration-time: 604800000 # 7天
  auth:
    ignore-urls:
      - "/user/**"
      - "/collect/**"
      - "/admin/song/**" #TODO 后端管理登录实现之后删除
      - "/admin/collect/**" #TODO 后端管理登录实现之后删除
      - "/oss/bigfile/**" #TODO 全部登录实现之后删除
#      - "/user/signup"
      - "/doc.html"
      - "/webjars/**"
      - "/v3/**"
      - "/favicon.ico"
      - "/banner"
      - "/song/**"
      - "/singer/**"
      - "/songList/**"  #TODO 用户端需要登录，后端现在开发中放行
      - "/oss/**" #TODO 用户端需要登录，后端现在开发中放行