package io.gitee.pkmer.core.infrastructure.persistence.comment.mybatis;

import io.gitee.pkmer.mybatis.annotations.SnowflakeId;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * generated by MyBatis Generator.
 * comment(评论表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2025/01/10
 */
@Data
public class Comment {
    @SnowflakeId
    private Long id;

    private Long userId;

    private Long songId;

    private Long songListId;

    private String content;

    private LocalDateTime createTime;

    private Byte type;

    private Integer up;
}